name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  call-ci-logic:
    name: Call CI Pipeline
    uses: ./.github/workflows/ci.yml
    permissions:
      contents: read
      packages: write

  deploy:
    name: Deploy to Production
    needs: call-ci-logic
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Ensure folder exists
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_PUBLIC_IP }} \
          "mkdir -p /home/${{ secrets.VPS_USERNAME }}/quanlykho"

      - name: Copy files to VPS (rsync)
        run: |
          rsync -avz \
            production-compose.yml \
            default.conf.template \
            ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_PUBLIC_IP }}:/home/${{ secrets.VPS_USERNAME }}/quanlykho/

      - name: Get short SHA for image tags
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: SSH and Deploy
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_PUBLIC_IP }} << 'EOF'

            set -e

            cd /home/${{ secrets.VPS_USERNAME }}/quanlykho

            # Create .env
            cat <<EOT > .env
            POSTGRES_HOST="${{ secrets.POSTGRES_HOST }}"
            POSTGRES_PORT="${{ secrets.POSTGRES_PORT }}"
            POSTGRES_DB="${{ secrets.POSTGRES_DB }}"
            POSTGRES_USER="${{ secrets.POSTGRES_USER }}"
            POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}"
            ADMIN_EMAIL="${{ secrets.ADMIN_EMAIL }}"
            ADMIN_PASSWORD="${{ secrets.ADMIN_PASSWORD }}"
            ADMIN_NAME="${{ secrets.ADMIN_NAME }}"
            CORS_ORIGIN="${{ vars.CORS_ORIGIN }}"
            JWT_SECRET="${{ secrets.JWT_SECRET }}"
            BACKEND_PORT="${{ vars.BACKEND_PORT }}"
            FRONTEND_PORT="${{ vars.FRONTEND_PORT }}"
            BACKEND_IMAGE_TAG="sha-${{ steps.vars.outputs.sha_short }}"
            FRONTEND_IMAGE_TAG="sha-${{ steps.vars.outputs.sha_short }}"
            NGINX_PORT="${{ vars.NGINX_PORT }}"
            BACKEND_HOST="${{ vars.BACKEND_HOST }}"
            FRONTEND_HOST="${{ vars.FRONTEND_HOST }}"
            API_DOMAIN="${{ vars.API_DOMAIN }}"
            WEB_DOMAIN="${{ vars.WEB_DOMAIN }}"
          EOT

            # Pull images
            docker pull ghcr.io/hbest1804/quanlykho-backend:sha-${{ steps.vars.outputs.sha_short }}
            docker pull ghcr.io/hbest1804/quanlykho-frontend:sha-${{ steps.vars.outputs.sha_short }}

            # Deploy
            docker compose -f production-compose.yml up -d --remove-orphans

            # Cleanup
            docker image prune -af

          EOF