name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  call-ci-logic:
    name: Call CI Pipeline
    uses: ./.github/workflows/ci.yml
    permissions:
      contents: read
      packages: write

  deploy:
    name: Deploy to Production
    needs: call-ci-logic
    runs-on: ubuntu-latest
    environment: PRODUCTION
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_PUBLIC_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "production-compose.yml,default.conf.template"
          target: "/home/${{ secrets.VPS_USERNAME }}/quanlykho"
          strip_components: 0

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.VPS_PUBLIC_IP }}
          username: ${{ vars.VPS_USERNAME }}
          key: ${{ vars.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /home/${{ vars.VPS_USERNAME }}/quanlykho
            cd /home/${{ vars.VPS_USERNAME }}/quanlykho
            
            # Setup .env file
            cat <<EOF > .env
            POSTGRES_HOST="${{ vars.POSTGRES_HOST }}"
            POSTGRES_PORT="${{ vars.POSTGRES_PORT }}"
            POSTGRES_DB="${{ vars.POSTGRES_DB }}"
            POSTGRES_USER="${{ vars.POSTGRES_USER }}"
            POSTGRES_PASSWORD="${{ vars.POSTGRES_PASSWORD }}"
            ADMIN_EMAIL="${{ vars.ADMIN_EMAIL }}"
            ADMIN_PASSWORD="${{ vars.ADMIN_PASSWORD }}"
            ADMIN_NAME="${{ vars.ADMIN_NAME }}"
            CORS_ORIGIN="${{ vars.CORS_ORIGIN }}"
            JWT_SECRET="${{ vars.JWT_SECRET }}"
            BACKEND_PORT="${{ vars.BACKEND_PORT }}"
            FRONTEND_PORT="${{ vars.FRONTEND_PORT }}"
            BACKEND_IMAGE_TAG="${{ github.sha }}"
            FRONTEND_IMAGE_TAG="${{ github.sha }}" 
            NGINX_PORT="${{ vars.NGINX_PORT }}"
            BACKEND_HOST="${{ vars.BACKEND_HOST }}"
            FRONTEND_HOST="${{ vars.FRONTEND_HOST }}"
            API_DOMAIN="${{ vars.API_DOMAIN }}"
            WEB_DOMAIN="${{ vars.WEB_DOMAIN }}"
            EOF

            # Pull latest images
            docker pull ghcr.io/hbest1804/quanlykho-backend:${{ github.sha }}
            docker pull ghcr.io/hbest1804/quanlykho-frontend:${{ github.sha }}

            # Run production compose
            docker-compose -f production-compose.yml up -d --remove-orphans
            # Clean up old images
            docker image prune -af
